---
- hosts: all
  become: yes

  roles:
    - geerlingguy.apache

  tasks:
    - name: Copy index.html
      copy:
        src: files/site/index.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: '0644'
